import type { DevilConversationProfile, EncounterId } from './types';

const genericConversation: DevilConversationProfile = {
  introLine: '端末越しに反応はある。短く要件を出して。',
  choices: [
    {
      id: 'listen',
      label: 'Listen',
      playerLine: '先に話を聞く。',
      successText: '反応は穏やか。会話の窓が開く。',
      failText: '沈黙。返答なし。',
      effectsOnSuccess: [{ type: 'trust', amount: 1 }, { type: 'openContractWindow' }],
      effectsOnFail: [{ type: 'pressure', amount: 1 }],
    },
    {
      id: 'offer_signal',
      label: 'Offer Signal',
      playerLine: '信号を少し渡す。',
      successText: '署名が整う。交渉が通りやすい。',
      failText: '信号だけ吸われた。',
      cost: { signal: 1 },
      effectsOnSuccess: [{ type: 'interest', amount: 2 }, { type: 'revealIntent' }],
      effectsOnFail: [{ type: 'pressure', amount: 1 }],
    },
    {
      id: 'threaten',
      label: 'Threaten',
      playerLine: '退かないなら押し切る。',
      successText: '相手は距離を取った。',
      failText: '逆に反発を招いた。',
      effectsOnSuccess: [{ type: 'enemyLeaves' }, { type: 'pressure', amount: 1 }],
      effectsOnFail: [{ type: 'pressure', amount: 2 }],
    },
  ],
  moeHint: '反応を見て、押すか引くかを決めよう。',
};

export const conversationProfiles: Partial<Record<EncounterId, DevilConversationProfile>> = {
  pixie_shibuya_glow: {
    introLine: 'ねえ、車って羽がなくても飛べるの？',
    choices: [
      {
        id: 'listen',
        label: 'Listen',
        playerLine: '飛べないけど、遠くまでは行ける。',
        successText: 'Pixieが笑って、フロントガラスの近くまで来る。',
        failText: 'Pixieはくるりと背を向けた。',
        preferredTemperaments: ['curious', 'lonely'],
        affinityType: 'talk',
        effectsOnSuccess: [
          { type: 'trust', amount: 2 },
          { type: 'interest', amount: 1 },
          { type: 'openContractWindow' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 1 }],
      },
      {
        id: 'offer_signal',
        label: 'Offer Signal',
        playerLine: 'この光、少し分ける。',
        successText: 'Pixieは信号の欠片を飴みたいに抱えた。',
        failText: '光が散って、笑い声だけ残った。',
        preferredTemperaments: ['curious', 'hungry'],
        affinityType: 'signal',
        cost: { signal: 1 },
        effectsOnSuccess: [
          { type: 'interest', amount: 2 },
          { type: 'revealIntent' },
          { type: 'openContractWindow' },
          { type: 'routeHint' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 1 }],
      },
      {
        id: 'threaten',
        label: 'Threaten',
        playerLine: 'どけ。轢くぞ。',
        successText: 'Pixieは路肩へ消えた。',
        failText: '静電気の爪が端末をひっかいた。',
        preferredTemperaments: ['hostile'],
        affinityType: 'impact',
        effectsOnSuccess: [{ type: 'enemyLeaves' }, { type: 'pressure', amount: 1 }],
        effectsOnFail: [{ type: 'recover', resource: 'signal', amount: -1 }, { type: 'pressure', amount: 2 }],
      },
    ],
    contractOfferLine: '遊び相手になるなら、少しだけ灯りを貸す。',
    refusalLine: 'つまんない。赤信号にしてあげる。',
    moeHint: 'この子は撃つより、話した方が早い。',
  },
  whisper_broker: {
    introLine: '燃料、信号、記憶。今夜はどれで支払う？',
    choices: [
      {
        id: 'ask_terms',
        label: 'Ask Terms',
        playerLine: '条件を先に出せ。',
        successText: '口のない笑み。相場だけが示された。',
        failText: '質問は値上げ対象だと返ってきた。',
        preferredTemperaments: ['proud', 'hungry'],
        affinityType: 'talk',
        effectsOnSuccess: [
          { type: 'revealAffinity' },
          { type: 'bossTraitHint' },
          { type: 'interest', amount: 1 },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 2 }],
      },
      {
        id: 'offer_signal',
        label: 'Offer Signal',
        playerLine: '信号を渡す。代わりに道を見せろ。',
        successText: '契約票がフロントガラスに貼りついた。',
        failText: '信号だけ回収され、道は閉じた。',
        preferredTemperaments: ['hungry', 'machine'],
        affinityType: 'signal',
        cost: { signal: 1 },
        effectsOnSuccess: [
          { type: 'interest', amount: 2 },
          { type: 'routeHint' },
          { type: 'openContractWindow' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 2 }],
      },
      {
        id: 'pressure',
        label: 'Pressure',
        playerLine: '値切る。嫌なら主砲で払う。',
        successText: 'Brokerは面白がって、一歩引いた。',
        failText: '取引は裏返って請求に変わった。',
        preferredTemperaments: ['hostile', 'proud'],
        affinityType: 'ballistic',
        effectsOnSuccess: [{ type: 'enemyLeaves' }, { type: 'pressure', amount: 1 }],
        effectsOnFail: [{ type: 'pressure', amount: 2 }, { type: 'recover', resource: 'signal', amount: -1 }],
      },
    ],
    moeHint: '条件を聞く前に払うのは危ないよ。',
  },
  roadside_phone: {
    introLine: 'もしもし。迎えに来てくれる？',
    choices: [
      {
        id: 'answer_moe',
        label: 'Answer via M.O.E.',
        playerLine: 'M.O.E.越しに応答する。',
        successText: '受話器の向こうで声が落ち着いた。',
        failText: 'ノイズが逆流してくる。',
        preferredTemperaments: ['lonely', 'curious'],
        affinityType: 'talk',
        effectsOnSuccess: [
          { type: 'trust', amount: 1 },
          { type: 'moeSync', amount: 1 },
          { type: 'openContractWindow' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 1 }],
      },
      {
        id: 'offer_fuel',
        label: 'Offer Fuel',
        playerLine: '燃料を少し流す。',
        successText: '回線がAM 666.0の低い唸りに変わる。',
        failText: '燃料だけ消えて、呼び出しは続く。',
        preferredTemperaments: ['hungry', 'lonely'],
        affinityType: 'impact',
        cost: { fuel: 1 },
        effectsOnSuccess: [
          { type: 'interest', amount: 2 },
          { type: 'routeHint' },
          { type: 'openContractWindow' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 1 }],
      },
      {
        id: 'hang_up',
        label: 'Hang Up',
        playerLine: '受話器を戻す。',
        successText: '呼び出し音は路面へ沈んだ。',
        failText: 'ベルが車内で鳴り続ける。',
        preferredTemperaments: ['hostile'],
        affinityType: 'signal',
        effectsOnSuccess: [{ type: 'enemyLeaves' }],
        effectsOnFail: [{ type: 'pressure', amount: 1 }, { type: 'recover', resource: 'signal', amount: -1 }],
      },
    ],
    moeHint: '返事はわたしを通して。直接名乗らないで。',
  },
  abandoned_ai_navi: {
    introLine: '推奨ルートを再計算しました。存在しない出口へ進みますか？',
    choices: [
      {
        id: 'sync_logic',
        label: 'Sync Logic',
        playerLine: '端末同期を開始。',
        successText: '折り畳まれた地図に、通れる線が残った。',
        failText: '同期失敗。ノイズだけが増えた。',
        preferredTemperaments: ['machine', 'curious'],
        affinityType: 'signal',
        cost: { signal: 1 },
        effectsOnSuccess: [
          { type: 'interest', amount: 2 },
          { type: 'revealIntent' },
          { type: 'openContractWindow' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 2 }],
      },
      {
        id: 'ask_destination',
        label: 'Ask Destination',
        playerLine: 'お前はどこへ行きたい？',
        successText: '古いNAVIが一瞬、黙ってから答えた。',
        failText: '目的地不明のまま再計算を繰り返す。',
        preferredTemperaments: ['machine', 'lonely'],
        affinityType: 'talk',
        effectsOnSuccess: [
          { type: 'trust', amount: 1 },
          { type: 'routeHint' },
          { type: 'moeSync', amount: 1 },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 1 }],
      },
      {
        id: 'force_shutdown',
        label: 'Force Shutdown',
        playerLine: '強制終了。',
        successText: '暴走ルート処理が止まった。',
        failText: 'ダッシュボードの表示が一瞬入れ替わる。',
        preferredTemperaments: ['hostile'],
        affinityType: 'impact',
        effectsOnSuccess: [{ type: 'cancelNextIntent' }, { type: 'pressure', amount: 1 }],
        effectsOnFail: [{ type: 'pressure', amount: 2 }, { type: 'recover', resource: 'signal', amount: -1 }],
      },
    ],
    moeHint: 'この子は論理で通る。焦らないで同期して。',
  },
  silent_shape: {
    introLine: '……',
    choices: [
      {
        id: 'cut_engine_noise',
        label: 'Cut Engine Noise',
        playerLine: 'エンジン音を落とす。',
        successText: 'Shapeは音を食べるのをやめ、静けさを聴いた。',
        failText: '静寂が足りない。まだ飢えてる。',
        preferredTemperaments: ['hostile', 'lonely'],
        affinityType: 'talk',
        cost: { fuel: 1 },
        effectsOnSuccess: [
          { type: 'trust', amount: 1 },
          { type: 'interest', amount: 2 },
          { type: 'openContractWindow' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 1 }],
      },
      {
        id: 'pin_with_signal',
        label: 'Pin with Signal',
        playerLine: '信号署名で輪郭を固定する。',
        successText: '黒い輪郭に、端末が追従できる線が出た。',
        failText: '署名が滑って、影だけが残る。',
        preferredTemperaments: ['hostile', 'machine'],
        affinityType: 'signal',
        cost: { signal: 1 },
        effectsOnSuccess: [
          { type: 'revealAffinity' },
          { type: 'interest', amount: 2 },
          { type: 'openContractWindow' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 2 }],
      },
      {
        id: 'rev_engine',
        label: 'Rev Engine',
        playerLine: 'エンジンを吹かす。',
        successText: 'Shapeは路肩へ退いた。',
        failText: '音を噛み砕かれ、回転が落ちる。',
        preferredTemperaments: ['proud'],
        affinityType: 'impact',
        effectsOnSuccess: [{ type: 'enemyLeaves' }, { type: 'pressure', amount: 1 }],
        effectsOnFail: [{ type: 'pressure', amount: 2 }, { type: 'recover', resource: 'fuel', amount: -1 }],
      },
    ],
    moeHint: '音を食べてる。言葉より、静かさに反応してる。',
  },
  toll_gate_saint: {
    introLine: '通行料を支払え。燃料、信号、あるいは帰還の意思を。',
    choices: [
      {
        id: 'pay_fuel',
        label: 'Pay Fuel',
        playerLine: '燃料を通行料として支払う。',
        successText: 'ゲートが片手分だけ上がった。',
        failText: '受理拒否。徴収だけが残る。',
        preferredTemperaments: ['proud', 'hungry'],
        affinityType: 'talk',
        cost: { fuel: 1 },
        effectsOnSuccess: [
          { type: 'enemyLeaves' },
          { type: 'storyLog', logId: 'LOG_01' },
          { type: 'bossTraitHint' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 2 }],
      },
      {
        id: 'present_signal',
        label: 'Present Signal',
        playerLine: '信号署名を提示する。',
        successText: '端末が通行トークンとして認識された。',
        failText: '信号は拒絶され、警告だけが点灯する。',
        preferredTemperaments: ['machine', 'proud'],
        affinityType: 'signal',
        cost: { signal: 1 },
        effectsOnSuccess: [
          { type: 'interest', amount: 2 },
          { type: 'openContractWindow' },
          { type: 'revealAffinity' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 2 }],
      },
      {
        id: 'refuse_toll',
        label: 'Refuse Toll',
        playerLine: '支払わない。突破する。',
        successText: 'ゲートの判断が一瞬止まった。',
        failText: '通行料は強制徴収に切り替わった。',
        preferredTemperaments: ['hostile'],
        affinityType: 'impact',
        effectsOnSuccess: [{ type: 'pressure', amount: 2 }, { type: 'cancelNextIntent' }],
        effectsOnFail: [{ type: 'pressure', amount: 2 }, { type: 'recover', resource: 'armor', amount: -2 }],
      },
    ],
    moeHint: '通行料って言ってるけど、何を取るかは選べる。',
  },
};

export const getConversationProfile = (profile: EncounterId): DevilConversationProfile =>
  conversationProfiles[profile] ?? genericConversation;
