import type { DevilConversationProfile, EncounterId } from './types';

const genericConversation: DevilConversationProfile = {
  introLine: '端末越しに反応はある。短く要件を出して。',
  choices: [
    {
      id: 'listen',
      label: 'Listen',
      playerLine: '先に話を聞く。',
      successText: '反応は穏やか。会話の窓が開く。',
      failText: '沈黙。返答なし。',
      effectsOnSuccess: [{ type: 'trust', amount: 1 }, { type: 'openContractWindow' }],
      effectsOnFail: [{ type: 'pressure', amount: 1 }],
    },
    {
      id: 'offer_signal',
      label: 'Offer Signal',
      playerLine: '信号を少し渡す。',
      successText: '署名が整う。交渉が通りやすい。',
      failText: '信号だけ吸われた。',
      cost: { signal: 1 },
      effectsOnSuccess: [{ type: 'interest', amount: 2 }, { type: 'revealIntent' }],
      effectsOnFail: [{ type: 'pressure', amount: 1 }],
    },
    {
      id: 'threaten',
      label: 'Threaten',
      playerLine: '退かないなら押し切る。',
      successText: '相手は距離を取った。',
      failText: '逆に反発を招いた。',
      effectsOnSuccess: [{ type: 'enemyLeaves' }, { type: 'pressure', amount: 1 }],
      effectsOnFail: [{ type: 'pressure', amount: 2 }],
    },
  ],
  moeHint: '反応を見て、押すか引くかを決めよう。',
};

export const conversationProfiles: Partial<Record<EncounterId, DevilConversationProfile>> = {
  pixie_shibuya_glow: {
    introLine: 'ねえ、車って羽がなくても飛べるの？',
    choices: [
      {
        id: 'answer_kindly',
        label: 'Answer Kindly',
        tone: 'friendly',
        playerLine: '飛べない。でも遠くまで走れるよ。窓のそばで見ていく？',
        successText: 'Pixie floats closer to the glass. 「遠くって、夜明けの色まで？」',
        failText: 'Pixieはくるりと背を向けた。',
        preferredTemperaments: ['curious', 'lonely'],
        affinityType: 'talk',
        followUp: {
          introLine: 'Pixie points at the road glow. 「夜明けの色って、どんな色？」',
          moeLine: '乗ってきた。ここは急がず、約束を小さく切ろう。',
          choices: [
            {
              id: 'pixie_listen_dawn',
              label: 'Promise Dawn',
              tone: 'friendly',
              playerLine: '青が少しずつ明るくなる色。見えたら、一緒に止まろう。',
              successText: 'Pixie presses both hands to the glass. The lane light turns soft blue.',
              failText: 'Pixie squints. 「それ、ほんと？」',
              preferredTemperaments: ['curious', 'lonely'],
              affinityType: 'talk',
              successBias: 0.2,
              effectsOnSuccess: [
                { type: 'trust', amount: 2 },
                { type: 'interest', amount: 1 },
                { type: 'revealIntent' },
                { type: 'openContractWindow' },
                { type: 'moeSync', amount: 1 },
              ],
              effectsOnFail: [{ type: 'pressure', amount: 1 }],
            },
            {
              id: 'pixie_listen_engine',
              label: 'Explain Simply',
              tone: 'curious',
              playerLine: '羽じゃなくて、エンジンと道で進む。飛ぶより少し安全。',
              successText: 'Pixie nods like she has discovered a new kind of wing.',
              failText: 'Pixie yawns. 「説明、長い。」',
              preferredTemperaments: ['curious'],
              affinityType: 'talk',
              effectsOnSuccess: [
                { type: 'trust', amount: 1 },
                { type: 'revealIntent' },
                { type: 'openContractWindow' },
              ],
              effectsOnFail: [{ type: 'pressure', amount: 1 }],
            },
            {
              id: 'pixie_listen_joke',
              label: 'Joke Back',
              tone: 'playful',
              playerLine: 'もし飛べたら、料金所が泣いちゃうね。',
              successText: 'Pixie bursts out laughing and taps a tiny spark across the dashboard.',
              failText: 'Pixie pouts. 「いま笑うところ？」',
              preferredTemperaments: ['curious'],
              affinityType: 'talk',
              effectsOnSuccess: [
                { type: 'interest', amount: 2 },
                { type: 'openContractWindow' },
              ],
              effectsOnFail: [{ type: 'pressure', amount: 1 }],
            },
          ],
        },
      },
      {
        id: 'play_along',
        label: 'Play Along',
        tone: 'playful',
        playerLine: '羽はないけど、ライトで夜を跳ねることはできる。',
        successText: 'Pixie brightens. 「じゃあ、飛ぶ合図して！」',
        failText: '光が散って、笑い声だけ残った。',
        preferredTemperaments: ['curious', 'lonely'],
        affinityType: 'talk',
        followUp: {
          introLine: 'Pixie hovers by the dashboard. 「合図の光、ひとつ見せて？」',
          moeLine: '向こうから光を欲しがった。渡すなら条件付き、渡さなくても会話は続く。',
          choices: [
            {
              id: 'pixie_signal_cabin_light',
              label: 'Blink Cabin Light',
              tone: 'playful',
              playerLine: '車内灯を一度だけ点ける。これが合図。',
              successText: 'Pixie catches the blink, polishes it, and sends it back cleaner.',
              failText: 'The light scatters into lane noise.',
              preferredTemperaments: ['curious', 'hungry'],
              affinityType: 'signal',
              cost: { signal: 1 },
              successBias: 0.25,
              effectsOnSuccess: [
                { type: 'interest', amount: 2 },
                { type: 'revealAffinity' },
                { type: 'recover', resource: 'signal', amount: 1 },
                { type: 'openContractWindow' },
              ],
              effectsOnFail: [{ type: 'recover', resource: 'signal', amount: -1 }, { type: 'pressure', amount: 1 }],
            },
            {
              id: 'pixie_signal_share',
              label: 'Trade for Route',
              tone: 'friendly',
              playerLine: '光を見せる代わりに、次の曲がり角を教えて。',
              successText: 'Pixie ties the blink into a tiny bow and leaves a route mark.',
              failText: 'Pixie hides the light behind her back.',
              preferredTemperaments: ['curious'],
              affinityType: 'signal',
              successBias: 0.15,
              effectsOnSuccess: [
                { type: 'interest', amount: 2 },
                { type: 'revealIntent' },
                { type: 'openContractWindow' },
              ],
              effectsOnFail: [{ type: 'pressure', amount: 1 }],
            },
            {
              id: 'pixie_signal_no_gift',
              label: 'No Gift Yet',
              tone: 'cautious',
              playerLine: 'まだあげない。先に名前を教えて。',
              successText: 'Pixie giggles. 「ケチ。でも、そういうの嫌いじゃない。」',
              failText: 'Pixie pouts and turns the dashboard light red.',
              preferredTemperaments: ['curious'],
              affinityType: 'talk',
              effectsOnSuccess: [
                { type: 'trust', amount: 1 },
                { type: 'revealIntent' },
                { type: 'openContractWindow' },
              ],
              effectsOnFail: [{ type: 'pressure', amount: 1 }],
            },
          ],
        },
      },
      {
        id: 'warn_gently',
        label: 'Warn Gently',
        tone: 'cautious',
        playerLine: 'そこは危ないよ。車道から少しだけ離れて。',
        successText: 'Pixie puffs her cheeks. 「命令？ それとも心配？」',
        failText: '静電気の爪が端末をひっかいた。',
        preferredTemperaments: ['curious', 'lonely'],
        affinityType: 'talk',
        followUp: {
          introLine: 'Pixie drifts toward the lane stripe, half sulking.',
          moeLine: '少しむくれた。心配として伝え直すか、通行を優先するか。',
          choices: [
            {
              id: 'pixie_threat_apologize',
              label: 'Say Sorry',
              tone: 'apologetic',
              playerLine: '心配だった。命令みたいに聞こえたなら、ごめん。',
              successText: 'Pixie peeks back in. 「……じゃあ、窓の光ひとつぶんだけ仲直り。」',
              failText: 'Pixie snaps, 「もう知らない！」 and kicks static into the terminal.',
              preferredTemperaments: ['lonely', 'curious'],
              affinityType: 'talk',
              successBias: 0.05,
              effectsOnSuccess: [
                { type: 'trust', amount: 1 },
                { type: 'openContractWindow' },
              ],
              effectsOnFail: [{ type: 'recover', resource: 'signal', amount: -1 }, { type: 'pressure', amount: 2 }],
            },
            {
              id: 'pixie_threat_double',
              label: 'Firm Warning',
              tone: 'firm',
              playerLine: '今は本当に危ない。離れて。これはお願いじゃない。',
              successText: 'Pixie clicks her tongue and vanishes into the guardrail lights.',
              failText: 'Pixie scratches the terminal with static.',
              preferredTemperaments: ['proud', 'hostile'],
              affinityType: 'talk',
              effectsOnSuccess: [{ type: 'enemyLeaves' }, { type: 'pressure', amount: 1 }],
              effectsOnFail: [{ type: 'recover', resource: 'signal', amount: -1 }, { type: 'pressure', amount: 2 }],
            },
            {
              id: 'pixie_threat_leave',
              label: 'Let Her Choose',
              tone: 'friendly',
              playerLine: '分かった。近くにいるなら、自分で決めていい。',
              successText: 'Pixie flickers once, still sulking, then slips into the lane lights.',
              failText: 'Pixie leaves a red spark on the terminal before vanishing.',
              preferredTemperaments: ['curious', 'lonely'],
              affinityType: 'talk',
              effectsOnSuccess: [{ type: 'enemyLeaves' }],
              effectsOnFail: [{ type: 'pressure', amount: 1 }, { type: 'enemyLeaves' }],
            },
          ],
        },
      },
    ],
    contractOfferLine: '遊び相手になるなら、少しだけ灯りを貸す。',
    refusalLine: 'つまんない。赤信号にしてあげる。',
    moeHint: 'この子は撃つより、話した方が早い。',
  },
  whisper_broker: {
    introLine: '燃料、信号、記憶。今夜はどれで支払う？',
    choices: [
      {
        id: 'ask_terms',
        label: 'Ask Terms',
        playerLine: '条件を先に出せ。',
        successText: '口のない笑み。相場だけが示された。',
        failText: '質問は値上げ対象だと返ってきた。',
        preferredTemperaments: ['proud', 'hungry'],
        affinityType: 'talk',
        effectsOnSuccess: [
          { type: 'revealAffinity' },
          { type: 'bossTraitHint' },
          { type: 'interest', amount: 1 },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 2 }],
      },
      {
        id: 'offer_signal',
        label: 'Offer Signal',
        playerLine: '信号を渡す。代わりに道を見せろ。',
        successText: '契約票がフロントガラスに貼りついた。',
        failText: '信号だけ回収され、道は閉じた。',
        preferredTemperaments: ['hungry', 'machine'],
        affinityType: 'signal',
        cost: { signal: 1 },
        effectsOnSuccess: [
          { type: 'interest', amount: 2 },
          { type: 'routeHint' },
          { type: 'openContractWindow' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 2 }],
      },
      {
        id: 'pressure',
        label: 'Pressure',
        playerLine: '値切る。嫌なら主砲で払う。',
        successText: 'Brokerは面白がって、一歩引いた。',
        failText: '取引は裏返って請求に変わった。',
        preferredTemperaments: ['hostile', 'proud'],
        affinityType: 'ballistic',
        effectsOnSuccess: [{ type: 'enemyLeaves' }, { type: 'pressure', amount: 1 }],
        effectsOnFail: [{ type: 'pressure', amount: 2 }, { type: 'recover', resource: 'signal', amount: -1 }],
      },
    ],
    moeHint: '条件を聞く前に払うのは危ないよ。',
  },
  roadside_phone: {
    introLine: 'もしもし。迎えに来てくれる？',
    choices: [
      {
        id: 'answer_moe',
        label: 'Answer via M.O.E.',
        playerLine: 'M.O.E.越しに応答する。',
        successText: '受話器の向こうで声が落ち着いた。',
        failText: 'ノイズが逆流してくる。',
        preferredTemperaments: ['lonely', 'curious'],
        affinityType: 'talk',
        effectsOnSuccess: [
          { type: 'trust', amount: 1 },
          { type: 'moeSync', amount: 1 },
          { type: 'openContractWindow' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 1 }],
      },
      {
        id: 'offer_fuel',
        label: 'Offer Fuel',
        playerLine: '燃料を少し流す。',
        successText: '回線がAM 666.0の低い唸りに変わる。',
        failText: '燃料だけ消えて、呼び出しは続く。',
        preferredTemperaments: ['hungry', 'lonely'],
        affinityType: 'impact',
        cost: { fuel: 1 },
        effectsOnSuccess: [
          { type: 'interest', amount: 2 },
          { type: 'routeHint' },
          { type: 'openContractWindow' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 1 }],
      },
      {
        id: 'hang_up',
        label: 'Hang Up',
        playerLine: '受話器を戻す。',
        successText: '呼び出し音は路面へ沈んだ。',
        failText: 'ベルが車内で鳴り続ける。',
        preferredTemperaments: ['hostile'],
        affinityType: 'signal',
        effectsOnSuccess: [{ type: 'enemyLeaves' }],
        effectsOnFail: [{ type: 'pressure', amount: 1 }, { type: 'recover', resource: 'signal', amount: -1 }],
      },
    ],
    moeHint: '返事はわたしを通して。直接名乗らないで。',
  },
  abandoned_ai_navi: {
    introLine: '推奨ルートを再計算しました。存在しない出口へ進みますか？',
    choices: [
      {
        id: 'sync_logic',
        label: 'Sync Logic',
        playerLine: '端末同期を開始。',
        successText: '折り畳まれた地図に、通れる線が残った。',
        failText: '同期失敗。ノイズだけが増えた。',
        preferredTemperaments: ['machine', 'curious'],
        affinityType: 'signal',
        cost: { signal: 1 },
        effectsOnSuccess: [
          { type: 'interest', amount: 2 },
          { type: 'revealIntent' },
          { type: 'openContractWindow' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 2 }],
      },
      {
        id: 'ask_destination',
        label: 'Ask Destination',
        playerLine: 'お前はどこへ行きたい？',
        successText: '古いNAVIが一瞬、黙ってから答えた。',
        failText: '目的地不明のまま再計算を繰り返す。',
        preferredTemperaments: ['machine', 'lonely'],
        affinityType: 'talk',
        effectsOnSuccess: [
          { type: 'trust', amount: 1 },
          { type: 'routeHint' },
          { type: 'moeSync', amount: 1 },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 1 }],
      },
      {
        id: 'force_shutdown',
        label: 'Force Shutdown',
        playerLine: '強制終了。',
        successText: '暴走ルート処理が止まった。',
        failText: 'ダッシュボードの表示が一瞬入れ替わる。',
        preferredTemperaments: ['hostile'],
        affinityType: 'impact',
        effectsOnSuccess: [{ type: 'cancelNextIntent' }, { type: 'pressure', amount: 1 }],
        effectsOnFail: [{ type: 'pressure', amount: 2 }, { type: 'recover', resource: 'signal', amount: -1 }],
      },
    ],
    moeHint: 'この子は論理で通る。焦らないで同期して。',
  },
  silent_shape: {
    introLine: '……',
    choices: [
      {
        id: 'cut_engine_noise',
        label: 'Cut Engine Noise',
        playerLine: 'エンジン音を落とす。',
        successText: 'Shapeは音を食べるのをやめ、静けさを聴いた。',
        failText: '静寂が足りない。まだ飢えてる。',
        preferredTemperaments: ['hostile', 'lonely'],
        affinityType: 'talk',
        cost: { fuel: 1 },
        effectsOnSuccess: [
          { type: 'trust', amount: 1 },
          { type: 'interest', amount: 2 },
          { type: 'openContractWindow' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 1 }],
      },
      {
        id: 'pin_with_signal',
        label: 'Pin with Signal',
        playerLine: '信号署名で輪郭を固定する。',
        successText: '黒い輪郭に、端末が追従できる線が出た。',
        failText: '署名が滑って、影だけが残る。',
        preferredTemperaments: ['hostile', 'machine'],
        affinityType: 'signal',
        cost: { signal: 1 },
        effectsOnSuccess: [
          { type: 'revealAffinity' },
          { type: 'interest', amount: 2 },
          { type: 'openContractWindow' },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 2 }],
      },
      {
        id: 'rev_engine',
        label: 'Rev Engine',
        playerLine: 'エンジンを吹かす。',
        successText: 'Shapeは路肩へ退いた。',
        failText: '音を噛み砕かれ、回転が落ちる。',
        preferredTemperaments: ['proud'],
        affinityType: 'impact',
        effectsOnSuccess: [{ type: 'enemyLeaves' }, { type: 'pressure', amount: 1 }],
        effectsOnFail: [{ type: 'pressure', amount: 2 }, { type: 'recover', resource: 'fuel', amount: -1 }],
      },
    ],
    moeHint: '音を食べてる。言葉より、静かさに反応してる。',
  },
  road_reaper: {
    introLine: 'この先、通行止め。迂回路は、まだ死んでいない方へ。',
    choices: [
      {
        id: 'ask_detour',
        label: 'Ask Detour',
        playerLine: '迂回路を示せ。まだ走れる道を',
        successText: 'Road Reaper points its warning baton toward a narrow lane.',
        failText: 'The baton snaps toward your windshield.',
        preferredTemperaments: ['proud'],
        affinityType: 'talk',
        successBias: -0.05,
        effectsOnSuccess: [
          { type: 'revealIntent' },
          { type: 'routeHint' },
          { type: 'pressure', amount: -1 },
        ],
        effectsOnFail: [
          { type: 'recover', resource: 'armor', amount: -1 },
          { type: 'pressure', amount: 1 },
        ],
      },
      {
        id: 'flash_headlights',
        label: 'Flash Headlights',
        playerLine: 'ヘッドライトで警告を返す',
        successText: 'The Reaper pauses, recognizing the signal as road language.',
        failText: 'The warning lights turn red.',
        preferredTemperaments: ['proud', 'machine'],
        affinityType: 'signal',
        effectsOnSuccess: [
          { type: 'cancelNextIntent' },
          { type: 'interest', amount: 1 },
        ],
        effectsOnFail: [{ type: 'pressure', amount: 2 }],
      },
      {
        id: 'force_through',
        label: 'Force Through',
        playerLine: '通行止めを突破する',
        successText: 'The Reaper steps aside just enough to pass.',
        failText: 'The lane narrows around the car.',
        preferredTemperaments: ['hostile', 'proud'],
        affinityType: 'impact',
        effectsOnSuccess: [
          { type: 'enemyLeaves' },
          { type: 'pressure', amount: 1 },
        ],
        effectsOnFail: [
          { type: 'recover', resource: 'armor', amount: -2 },
          { type: 'pressure', amount: 2 },
        ],
      },
    ],
    moeHint: '会話は通じにくい。でも“道”の話なら反応するかも。',
  },
  toll_gate_saint: {
    introLine: '通行料を支払え。燃料、信号、あるいは帰還の意思を。',
    choices: [
      {
        id: 'pay_fuel',
        label: 'Pay Fuel',
        playerLine: '燃料を通行料として支払う。',
        successText: 'The barrier lifts by one hand’s width.',
        failText: 'The toll is not accepted as fuel.',
        preferredTemperaments: ['proud', 'hungry'],
        affinityType: 'talk',
        cost: { fuel: 1 },
        effectsOnSuccess: [
          { type: 'enemyLeaves' },
          { type: 'storyLog', logId: 'LOG_01' },
          { type: 'bossTraitHint' },
        ],
        effectsOnFail: [{ type: 'recover', resource: 'fuel', amount: -1 }, { type: 'pressure', amount: 1 }],
      },
      {
        id: 'present_signal',
        label: 'Present Signal',
        playerLine: '信号署名を提示する。',
        successText: 'The Saint recognizes your terminal as a valid toll token.',
        failText: 'The signature is stamped INVALID.',
        preferredTemperaments: ['machine', 'proud'],
        affinityType: 'signal',
        cost: { signal: 1 },
        effectsOnSuccess: [
          { type: 'interest', amount: 2 },
          { type: 'openContractWindow' },
          { type: 'revealAffinity' },
        ],
        effectsOnFail: [{ type: 'recover', resource: 'signal', amount: -1 }, { type: 'pressure', amount: 1 }],
      },
      {
        id: 'refuse_toll',
        label: 'Refuse Toll',
        playerLine: '支払わない。突破する。',
        successText: 'The gate hesitates.',
        failText: 'The toll is taken by force.',
        preferredTemperaments: ['hostile'],
        affinityType: 'impact',
        effectsOnSuccess: [{ type: 'pressure', amount: 2 }, { type: 'cancelNextIntent' }],
        effectsOnFail: [{ type: 'pressure', amount: 2 }, { type: 'recover', resource: 'armor', amount: -2 }],
      },
    ],
    moeHint: '通行料って言ってるけど、何を取るかは選べる。',
  },
};

export const getConversationProfile = (profile: EncounterId): DevilConversationProfile =>
  conversationProfiles[profile] ?? genericConversation;
